# See https://aka.ms/yaml
# This pipeline to be run on tags creation

pr: none
trigger:
  tags:
    include:
      - v*

resources:
  containers:
    - container: centos7
      image: ucfconsort.azurecr.io/ucx/centos7:1
      endpoint: ucfconsort_registry
    - container: centos7_cuda10_1
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/centos7-mofed5.0-cuda10.1:1
    - container: centos7_cuda10_2
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/centos7-mofed5.0-cuda10.2:1
    - container: ubuntu16_cuda10_1
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/ubuntu16.04-mofed5.0-cuda10.1:1
    - container: ubuntu16_cuda10_2
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/ubuntu16.04-mofed5.0-cuda10.2:1
    - container: ubuntu18_cuda10_1
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/ubuntu18.04-mofed5.0-cuda10.1:1
    - container: ubuntu18_cuda10_2
      image: rdmz-harbor.rdmz.labs.mlnx/ucx/ubuntu18.04-mofed5.0-cuda10.2:1

stages:
  - stage: Release
    jobs:
      - template: az-distro-release.yml
      # - template: az-jucx-publish.yml
      #   parameters:
      #     target: publish-release
